title: AIVX
description: .
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark # or auto if you want it to switch with your system settings.
  nav_pages:
      - /projects/
      - blog.md
      - about.md
 